version: "3"
services:
    frontend:
        container_name: reactjs_frontend
        build:
            context: ./client
            dockerfile: Dockerfile
        image: reactjsaa
        ports:
            - "80:80"
        volumes:
            - ./client:/usr/src/app
        depends_on:
            - backend
    backend:
        container_name: golang_backendaa 
        build:
            context: ./server
            dockerfile: Dockerfile
        image: golangaa
        ports:
            - "8080:8080"
        volumes:
            - ./server:/gofolder
