version: "3"
services:
    frontend:
        container_name: reactjs_frontend 
        build:
            context: ./client
            dockerfile: Dockerfile
        image: reactjsaa
        ports:
            - "8082:8082"
        volumes:
            - ./client:/usr/src/app
        depends_on:
            - backend
    backend:
        container_name: golang_backendaa 
        build:
            context: ./server
            dockerfile: Dockerfile
        image: golangaa
        ports:
            - "8081:8081"
        volumes:
            - ./server:/gofolder
